const symptoms = [
    { id: 1, str: "itching" },
    { id: 2, str: "skin Rash" },
    { id: 3, str: "Nodal Skin Eruptions" },
    { id: 4, str: "Continuous Sneezing" },
    { id: 5, str: "Shivering" },
    { id: 6, str: "Chills" },
    { id: 7, str: "Joint Pain" },
    { id: 8, str: "Stomach Pain" },
    { id: 9, str: "Acidity" },
    { id: 10, str: "Ulcers on Tongue" },
    { id: 11, str: "Muscle Wasting" },
    { id: 12, str: "Vomiting" },
    { id: 13, str: "Burning Micturition" },
    { id: 14, str: "Spotting Urination" },
    { id: 15, str: "Fatigue" },
    { id: 16, str: "Weight Gain" },
    { id: 17, str: "Anxiety" },
    { id: 18, str: "Cold Hands and Feets" },
    { id: 19, str: "Moood Swings" },
    { id: 20, str: "Weight Loss" },
    { id: 21, str: "Restlessness" },
    { id: 22, str: "Lethary" },
    { id: 23, str: "Patches in throat" },
    { id: 24, str: "Irregular Sugar Level" },
    { id: 25, str: "Cough" },
    { id: 26, str: "High Fever" },
    { id: 27, str: "Sunken Eyes" },
    { id: 28, str: "Breathlessness" },
    { id: 29, str: "Sweating" },
    { id: 30, str: "Dehydration" },
    { id: 31, str: "Indigestion" },
    { id: 32, str: "Head Ache" },
    { id: 33, str: "Yellowish Skin" },
    { id: 34, str: "Dark Urine" },
    { id: 35, str: "Nausea" },
    { id: 36, str: "Loss Of Appetite" },
    { id: 37, str: "Pain Behind the Eyes" },
    { id: 38, str: "Back Pain" },
    { id: 39, str: "Constipation" },
    { id: 40, str: "Abdominal Pain" },
    { id: 41, str: "Diarrhoea" },
    { id: 42, str: "Mild Fever" },
    { id: 43, str: "Yellow Fever" },
    { id: 44, str: "Yellowing Of Eyes" },
    { id: 45, str: "Acute Liver Failure" },
    { id: 46, str: "Fluid Overload" },
    { id: 47, str: "Swelling Of Stomach" },
    { id: 48, str: "Swelled Lymph NOdes" },
    { id: 49, str: "Melaise" },
    { id: 50, str: "Blurred and Distorted Vision" },
    { id: 51, str: "Phegm" },
    { id: 52, str: "Throat Irritation" },
    { id: 53, str: "Redness Of Eyes" },
    { id: 54, str: "Sinus Pressure" },
    { id: 55, str: "Runny Nose" },
    { id: 56, str: "Congestion" },
    { id: 57, str: "CHest Pain" },
    { id: 58, str: "Weakness in Limbs" },
    { id: 59, str: "Fast Heart Rate" },
    { id: 60, str: "Pain During Bowel Movements" },
    { id: 61, str: "Pain in Anal Region" },
    { id: 62, str: "Bloody Stool" },
    { id: 63, str: "Irritation in Anus" },
    { id: 64, str: "Neck Pain" },
    { id: 65, str: "Dizziness" },
    { id: 66, str: "Cramps" },
    { id: 67, str: "Bruising" },
    { id: 68, str: "Obesity" },
    { id: 69, str: "Swollen Legs" },
    { id: 70, str: "Swollen Blood Vessels" },
    { id: 71, str: "Puffy Face and Eyes" },
    { id: 72, str: "Enlarged Thyroid" },
    { id: 73, str: "Brittle Nails" },
    { id: 74, str: "Swollen Extremeties" },
    { id: 75, str: "Excessive Hunger" },
    { id: 76, str: "Extra Marital Contracts" },
    { id: 77, str: "Drying and tingling Lips" },
    { id: 78, str: "Slurred Speech" },
    { id: 79, str: "Knee Pain" },
    { id: 80, str: "Hip Joint Pain" },
    { id: 81, str: "Muscle Weakness" },
    { id: 82, str: "Stiff Neck" },
    { id: 83, str: "Sweling Joints" },
    { id: 84, str: "Movement Stiffness" },
    { id: 85, str: "Spinning Movements" },
    { id: 86, str: "Loss of Balance" },
    { id: 87, str: "Unsteadiness" },
    { id: 88, str: "Weakness Of One Body Side" },
    { id: 89, str: "Loss Of Smell" },
    { id: 90, str: "Bladder Discomfort" },
    { id: 91, str: "Foul Smell Of Urine" },
    { id: 92, str: "Continous Feel Of Urine" },
    { id: 93, str: "Passage of Gas" },
    { id: 94, str: "Internal itching" },
    { id: 95, str: "Toxic Look (typhos)" },
    { id: 96, str: "Depression" },
    { id: 97, str: "Irritability" },
    { id: 98, str: "Muscle Pain" },
    { id: 99, str: "Altered Sensorium" },
    { id: 100, str: "Red Spots Over Body" },
    { id: 101, str: "Belly Pain" },
    { id: 102, str: "Abnormal Menstruation" },
    { id: 103, str: "Dischromic Patches" },
    { id: 104, str: "Watering From Eyes" },
    { id: 105, str: "Increased Appetite" },
    { id: 106, str: "Polyuria" },
    { id: 107, str: "Family History" },
    { id: 108, str: "Mucoid Sputum" },
    { id: 109, str: "Rusty Sputum" },
    { id: 110, str: "Lack Of Concentration" },
    { id: 111, str: "Visual Disturbances" },
    { id: 112, str: "Receiving Blood Transfusion" },
    { id: 113, str: "Receiving Unsterile Injections" },
    { id: 114, str: "Coma" },
    { id: 115, str: "Stomach Bleeding" },
    { id: 116, str: "Distension of Abdomen" },
    { id: 117, str: "History Of Alcohol Consumption" },
    { id: 118, str: "Fluid Overdose" },
    { id: 119, str: "Blood in Sputum" },
    { id: 120, str: "Prominent Veins On Calf" },
    { id: 121, str: "Palpitations" },
    { id: 122, str: "Painful walking" },
    { id: 123, str: "Pus Filled Pimples" },
    { id: 124, str: "Black Heads" },
    { id: 125, str: "Scurring" },
    { id: 126, str: "Skin Peeling" },
    { id: 127, str: "Silver Like Dusting" },
    { id: 128, str: "Small Dents in Nails" },
    { id: 129, str: "Inflammatory Nails" },
    { id: 130, str: "Blister" },
    { id: 131, str: "Red Sore Around Nose" },



  ];
  

  
  export default symptoms;
